# Generated by Django 5.1.6 on 2025-03-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='full_text',
        ),
        migrations.AddField(
            model_name='news',
            name='subheader',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='news',
            table=None,
        ),
    ]
