# Generated by Django 5.1.5 on 2025-01-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='entity_type',
            field=models.CharField(max_length=20),
        ),
    ]
