# Generated by Django 5.1.6 on 2025-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
