# Generated by Django 5.1.6 on 2025-03-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, help_text='0 означает, что ограничений нет', verbose_name='Максимальное количество участников'),
        ),
    ]
