# Generated by Django 5.1.6 on 2025-04-06 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fcmtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.BooleanField(default=True)),
                ('moderation', models.BooleanField(default=True)),
                ('likes_comments', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
