# Generated by Django 5.1.6 on 2025-04-07 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pushnotificationsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='fcmtoken',
            table=None,
        ),
    ]
