# Generated by Django 5.1.6 on 2025-04-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_fcmtoken_user_alter_fcmtoken_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
