# Generated by Django 5.0.14 on 2025-04-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_comment_updated_at_news_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('approved', 'Принят'), ('rejected', 'Отклонен')], default='rejected', max_length=10)),
            ],
        ),
    ]
