# Generated by Django 5.1.6 on 2025-04-08 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_comment_updated_at_news_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['from_user', 'to_user', 'sent_at'], name='messages_from_us_111001_idx'),
        ),
    ]
