# Generated by Django 5.1.6 on 2025-04-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_message_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationsetting',
            name='messages',
            field=models.BooleanField(default=True),
        ),
    ]
